# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8949ce00101d7a8d06ed70ae6dd53104992f5d5717dbeccefc1df64565ea26acf1c80312f4588e09084649d0fe100f8684a2df2af29b88a4a4bef00fa57965c9

test:
  secret_key_base: 84f1670b6420fa3d2329bfcfc607ebc0a6dee0e208abde23ec5d554179cb1d888329ab8dad373cb68477b4a9843bbb85d7c89f7cb679cf3d424743e617e9f713

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
